### ISSUE TITLE
SNG Decode Issue

### ISSUE THREAD

**Issue by jackjackwarren** [mdsitton/SngFileFormat#4]
Hi, I am having an error message appear when using the program to decode the default clone hero songs. I am using the 0.2.0 build. The error is attached below:

System.FormatException: Invalid SNG file identifier
   at SngLib.SngSerializer.LoadSngFile(String path)
   at SngCli.SngDecode.DecodeSong(String sngPath)
   at SngCli.SngDecode.<>c.<<ProcessSongs>b__5_0>d.MoveNext()

Please can you advise what may be causing this and any steps I can take to resolve.

Thanks.

**Comment by sonicfind** [comment]
The built-in songs are an encrypted CH-only version of sng. You can’t decode them with this tool by design.

**Comment by mdsitton** [comment]
Yes as @sonicfind said the built in clone hero songs use a completely different format from this public format. If what you are trying to decode is something different from that then i can re-open this.
